name: Build & Push Portfolio Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo download
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ DockerHub login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3️⃣ Build image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/football-portfolio:hasnain .

      # 4️⃣ Push image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/football-portfolio:hasnain
